
rust_test:
  image: "rust:1.26-stretch"
  variables:
    TEST_DATABASE_URL: "postgres://postgres@localhost/fatcat_test"
  services:
    - "postgres:9.6"
  before_script:
    - cargo install diesel_cli --version 1.2
  script:
    - rustc --version && cargo --version && diesel --version
    - cd rust
    - diesel database reset && diesel migration run
    - cargo build
    - cargo test -- --test-threads 1

rust_build_release:
  only:
    - tags  # doesn't build for most commits; only tagged
  image: "rust:1.26-stretch"
  script:
    - rustc --version && cargo --version
    - cd rust
    - cargo build --release
    - cargo doc
  artifacts:
    paths:
    - rust/target/release/fatcat*
    - rust/target/doc/fatcat*
    - rust/target/doc/*.css
    - rust/target/doc/*.js
    - rust/target/doc/*.woff
    - rust/target/doc/*.svg
    expire_in: 1 year

python_unittest_and_lint:
  image: python:3.6-stretch
  before_script:
    - apt update -qy
    - apt install -y python3-dev python3-pip python3-wheel
    - pip3 install pipenv
    - pipenv --version
  script:
    - cd python
    - pipenv install --dev --deploy
    - pipenv run pytest --cov
    # Still too rigorous
    #- pipenv run pylint --disable bad-continuation,arguments-differ,unidiomatic-typecheck fatcat
