image: python:3.6-stretch
before_script:
  - apt update -qy
  - apt install -y python3-dev python3-pip python3-wheel
  - pip3 install pipenv
  - pipenv --version

unittest_and_lint:
  script:
    - pipenv install --dev --deploy
    - pipenv run pytest --cov
    - pipenv run pylint --disable bad-continuation,arguments-differ,unidiomatic-typecheck fatcat
