consumes:
- application/json
info:
  description: A scalable, versioned, API-oriented catalog of bibliographic entities
    and file metadata
  title: fatcat
  version: 0.1.0
paths: {}
produces:
- application/json
schemes:
- http
swagger: "2.0"

definitions:
  error:
    type: object
    required:
      - message
    properties:
      message:
        type: string
  creator_entity:
    type: object
    required:
      - ident
      - state
    properties:
      state: 
        type: string
        # actually enum of: (wip, active, redirect, deleted)
      ident:
        type: string
      revision:
        type: string
      redirect:
        type: string
      name:
        type: string
      orcid:
        type: string

paths:
  /creator:
    post:
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/creator_entity"
      responses:
        201:
          description: created
          schema:
            $ref: "#/definitions/creator_entity"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
  /creator/{id}:
    parameters:
      - name: id
        in: path
        type: string
        required: true
    get:
      responses:
        200:
          description: fetch a single creator by id
          schema:
            $ref: "#/definitions/creator_entity"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
# /creator/lookup:

# /editgroup:
# /editgroup/{id}:
# /editgroup/{id}/accept:

# /editor/{username}:
# /editor/{username}/changelog:
