[package]
name = "fatcat"
version = "0.1.0"
authors = ["Bryan Newbold <bnewbold@archive.org>"]

[workspace]
members = ["fatcat-api"]

[dependencies]
fatcat-api = {version = "*", path = "fatcat-api"}
diesel = { version = "1.0.0", features = ["postgres"] }
dotenv = "0.9.0"
clap = "*"
error-chain = "0.11"
r2d2 = "*"
r2d2-diesel = "*"

# API server
chrono = { version = "0.4", features = ["serde"] }
futures = "0.1"
hyper = "0.10"
iron = "0.5"
iron-slog = "*"
iron-test = "*"
swagger = "0.7"
slog = "^2.0"
slog-term = "*"
slog-async = "*"

[dependencies.iron_diesel_middleware]
git = "https://github.com/darayus/iron-diesel-middleware"

#hyper-openssl = {version = "0.2", optional = true}
#hyper-tls = {version = "0.1.2", optional = true}
#tokio-core = "0.1.6"
#tokio-proto = "0.1.1"

# TODO
#sentry = "*"
#cadence = "*"
#frank_jwt = "*"
